const ACTIONS = Object.freeze({
    LOGIN: 'LOGIN',
    LOGIN_ASYNC: 'LOGIN_ASYNC',
    REGISTER: 'REGISTER',
    REGISTER_ASYNC: 'REGISTER_ASYNC',
    IS_LOADING: 'IS_LOADING',
    ALERT: 'ALERT',
    ALERT_ASYNC: 'ALERT_ASYNC',
    CASE: 'CASE',
    CASE_ASYNC: 'CASE_ASYNC',
    SET_MY_ACCOUNT: 'MY_ACCOUNT',
    SET_MY_ACCOUNT_ASYNC: 'MY_ACCOUNT_ASYNC',
    IS_POP_UP_ACTIVE: 'IS_POP_UP_ACTIVE',
    SET_LOGIN_NAME: 'SET_LOGIN_NAME',
    SET_LOGIN_NAME_ASYNC: 'SET_LOGIN_NAME_ASYNC',
    SET_PASSWORD: 'SET_PASSWORD',
    SET_PASSWORD_ASYNC: 'SET_PASSWORD_ASYNC',
    RESET_PASSWORD: 'RESET_PASSWORD',
    RESET_PASSWORD_ASYNC: 'RESET_PASSWORD_ASYNC',
    SET_CATALOG_PAGES: 'SET_CATALOG_PAGES',
    SET_CATALOG_PAGES_ASYNC: 'SET_CATALOG_PAGES_ASYNC',
});

export const ACCESS_TOKEN = 'accessToken'
export const isDevelopment = !process.env.NODE_ENV || process.env.NODE_ENV === 'development'

export default ACTIONS;